name: Construire SP Connect

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Compilation Android
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Donner les permissions à Gradle
        run: chmod +x gradlew
        working-directory: application

      - name: Construire l'application
        run: ./gradlew assembleDebug
        working-directory: application

      - name: Publier l'APK
        uses: actions/upload-artifact@v4
        with:
          name: SP-Connect-debug
          path: application/build/outputs/apk/debug/*.apk
